name: Test Notifications

on:
  workflow_run:
    workflows: ["Test Automation Pipeline"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    
    steps:
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ github.event.workflow_run.conclusion }}
        channel: '#qa-automation' # Ajuste para seu canal
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        text: |
          🧪 Test Automation Pipeline - ${{ github.event.workflow_run.conclusion }}
          
          Repository: ${{ github.repository }}
          Branch: ${{ github.event.workflow_run.head_branch }}
          Commit: ${{ github.event.workflow_run.head_sha }}
          
          Workflow: ${{ github.event.workflow_run.name }}
          Run ID: ${{ github.event.workflow_run.id }}
          
          View run: ${{ github.event.workflow_run.html_url }}
          
          📊 Allure Report: https://${{ github.repository_owner }}.github.io/${{ github.repository }}/allure-report/
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
